# Generated by Django 3.1.1 on 2020-09-25 14:26

from django.db import migrations
import list.fields


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=list.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
